version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgresql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  wiremock:
    image: wiremock/wiremock:2.32.0
    restart: always
    ports:
      - '8081:8080'
    volumes:
      - ./wiremock:/home/wiremock
volumes:
  db:
    driver: local